djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from djangoProject.views import landing_page

from problems.views import problem_list,problem_detail
from submissions.views import submit_code, submission_result

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    # path('home/', home, name='home'),
    path('users/', include('users.urls'), name='users'),
    path('', include('problems.urls'), name='problems'),
    path('', include('submissions.urls'), name='submissions'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problems/urls.py
# problems/urls.py
from django.urls import path
from . import views

app_name = 'problems'

urlpatterns = [
    path('problems/', views.problem_list, name='problem_list'),
    path('<int:pk>/', views.problem_detail, name='problem_detail'),
    path('problems/<slug>/', views.theme_list, name='problem-of-theme'),
]

submissions/urls.py
# problems/urls.py
from django.urls import path
from .views import submit_code, submission_result

app_name = 'submissions'
urlpatterns = [
    path('submit/<int:problem_id>/', submit_code, name='submit_code'),
    path('submission/<int:pk>/', submission_result, name='submission_result'),
]

users/urls.py
from django.contrib.auth.views import (PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)
from django.urls import path, reverse_lazy

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView, verify_email

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('verify-email/', verify_email, name='verify_email'),

    path('password-change/', PasswordChangeView.as_view(), name="password_change"),
    path('password-change-done/', PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name="password_reset"),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url = reverse_lazy("users:password_reset_complete")), name="password_reset_confirm"),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

problems/models.py
from django.db import models
from django.urls import reverse
from slugify import slugify

from users.models import CustomUser

class Theme(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Theme, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('problem-of-theme', args=[self.slug])

    def __str__(self):
        return self.name


class Problem(models.Model):
    class Level(models.TextChoices):
        EASY = 'easy', 'EASY'
        MEDIUM = 'medium', 'MEDIUM'
        HARD = 'hard', 'HARD'

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, null=True, blank=True)
    level = models.CharField(
        max_length=12,
        choices=Level.choices,
        default=Level.EASY
    )
    input_format = models.TextField()
    output_format = models.TextField()
    sample_input = models.TextField()
    sample_output = models.TextField()
    test_cases = models.TextField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Problem, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class UserProblem(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} -> {self.problem}'

    # def get_problems(request):
    #     problems = [i.title for i in Problem.objects.filter(user=request.user)]
    #     return problems

problems/views.py
# problems/views.py
from django.shortcuts import render, get_object_or_404
from .models import Problem, Theme, UserProblem


def problem_list(request):
    problems = Problem.objects.all()
    query = request.GET.get('q')
    if query:
        problems = problems.filter(title__icontains=query)

    themes = Theme.objects.all()

    context = {'problems': problems, 'themes': themes}

    if request.user.is_authenticated:
        user_problems = [i.problem.title for i in UserProblem.objects.filter(user=request.user)]
        context = {'problems': problems, 'themes': themes, 'user_problems': user_problems}
    return render(request, 'problems/problem_list.html', context)

def problem_detail(request, pk):
    problem = get_object_or_404(Problem, pk=pk)
    return render(request, 'problems/problem_detail.html', {'problem': problem})


def theme_list(request, slug):
    themes = Theme.objects.all()
    theme = Theme.objects.get(slug=slug)
    problems = Problem.objects.filter(theme=theme)
    context = {'theme': theme, 'problems': problems, 'themes': themes}

    if request.user.is_authenticated:
        user_problems = [i.problem.title for i in UserProblem.objects.filter(user=request.user)]
        context = {'theme': theme, 'problems': problems, 'themes': themes, 'user_problems': user_problems}

    return render(request, 'problems/theme.html', context)

# problems/views.py
# from django.shortcuts import render, get_object_or_404
# from .models import Problem

# def problem_list(request):
#     problems = Problem.objects.all()
#     return render(request, 'problems/problem_list.html', {'problems': problems})
#
# def problem_detail(request, pk):
#     problem = get_object_or_404(Problem, pk=pk)
#     return render(request, 'problems/problem_detail.html', {'problem': problem})

templates/problems/problem_detail.html
<!-- templates/problems/problem_detail.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{ problem.title }} {% endblock %}


{% block content %}

    <h1>{{ problem.title }}</h1>
    <p>{{ problem.description }}</p>
    <h3>Input Format</h3>
    <p>{{ problem.input_format }}</p>
    <h3>Output Format</h3>
    <p>{{ problem.output_format }}</p>
    <h3>Sample Input</h3>
    <pre>{{ problem.sample_input }}</pre>
    <h3>Sample Output</h3>
    <pre>{{ problem.sample_output }}</pre>
    <a href="{% url 'submissions:submit_code' problem.pk %}" class="btn btn-primary">Submit Your Solution</a>
    <a href="{% url 'problems:problem_list' %}" class="btn btn-secondary">Back to Problems</a>

{% endblock %}

templates/problems/problem_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Masalalar to'plami{% endblock title %}


{% block content %}
    <h1>Problem List</h1>
    <div class="row">
        <div class="col-2 border-right">
            <h5>Mavzular</h5>
            {% for theme in themes %}
                <a class="btn btn-sm mb-1" href="{% url 'problems:problem-of-theme' theme.slug %}">{{ theme.name }}</a>
            {% endfor %}
        </div>
        <div class="col-9">
            <table class="table">
                <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>Nomi ( {{ problems|length }} )</th>
                        <th>Darajasi</th>
                        <th>Mavzusi</th>
                        <th>Holati ( {{ user_problems|length }} )</th>
                    </tr>
                </thead>
                <tbody>
                    {% for problem in problems %}

                    <tr class="">
                        <th>
                            {{ forloop.counter }}
                        </th>
                        <th>
                            <a href="{% url 'problems:problem_detail' problem.pk %}">{{ problem.title }}</a>
                        </th>
                        <th>
                            {{ problem.level }}
                        </th>
                        <th>
                            {{ problem.theme }}
                        </th>
                        <th>
                            {% if problem.title in user_problems %}
                                <svg style="width: 20px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                    <path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM369 209L241 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L335 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z" fill="green"/>
                                </svg>
                            {% else %}
                                <svg style="width: 20px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                                    <path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z" fill="red"/>
                                </svg>
                            {% endif %}
                        </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/problems/theme.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Masalalar to'plami{% endblock title %}


{% block content %}

    <div class="row">
        <div class="col-2 border-right">
            <h5>Mavzular</h5>
            {% for theme in themes %}
                <a class="btn btn-sm mb-1" href="{% url 'problems:problem-of-theme' theme.slug %}">{{ theme.name }}</a>
            {% endfor %}
        </div>
        <div class="col-10">
            <ul class="problem-list">
                {% if problems %}
                    <h3>{{ theme.name }}ga oid masalalar</h3>
                    <table class="table">
                        <thead class="table-dark">
                            <tr>
                                <th>#</th>
                                <th>Nomi </th>
                                <th>Darajasi</th>
                                <th>Mavzusi</th>
                                <th>Holati</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for problem in problems %}

                            <tr class="">
                                <th>
                                    {{ forloop.counter }}
                                </th>
                                <th>
                                    <a href="{% url 'problems:problem_detail' problem.pk %}">{{ problem.title }}</a>
                                </th>
                                <th>
                                    {{ problem.level }}
                                </th>
                                <th>
                                    {{ problem.theme }}
                                </th>
                                <th>
                                    {% if problem.title in user_problems %}
                                        <svg style="width: 20px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                            <path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM369 209L241 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L335 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z" fill="green"/>
                                        </svg>
                                    {% else %}
                                        <svg style="width: 20px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                                            <path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z" fill="red"/>
                                        </svg>
                                    {% endif %}
                                </th>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h5>{{ theme.name }}ga oid masalalar hozircha mavjud emas</h5>
                {% endif %}
            </ul>
        </div>
    </div>

{% endblock %}