djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from djangoProject.views import landing_page

from problems.views import problem_list,problem_detail
from submissions.views import submit_code, submission_result

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    # path('home/', home, name='home'),
    path('users/', include('users.urls'), name='users'),
    path('', include('problems.urls'), name='problems'),
    path('', include('submissions.urls'), name='submissions'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problems/urls.py
# problems/urls.py
from django.urls import path
from . import views

app_name = 'problems'

urlpatterns = [
    path('problems/', views.problem_list, name='problem_list'),
    path('<int:pk>/', views.problem_detail, name='problem_detail'),
    path('problems/<slug>/', views.theme_list, name='problem-of-theme'),
]

users/urls.py
from django.contrib.auth.views import (PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)
from django.urls import path, reverse_lazy

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView, verify_email

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('verify-email/', verify_email, name='verify_email'),

    path('password-change/', PasswordChangeView.as_view(), name="password_change"),
    path('password-change-done/', PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name="password_reset"),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url = reverse_lazy("users:password_reset_complete")), name="password_reset_confirm"),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

problems/models.py
from django.db import models
from django.urls import reverse
from slugify import slugify

from users.models import CustomUser

class Theme(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Theme, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('problem-of-theme', args=[self.slug])

    def __str__(self):
        return self.name


class Problem(models.Model):
    class Level(models.TextChoices):
        EASY = 'easy', 'EASY'
        MEDIUM = 'medium', 'MEDIUM'
        HARD = 'hard', 'HARD'

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, null=True, blank=True)
    level = models.CharField(
        max_length=12,
        choices=Level.choices,
        default=Level.EASY
    )
    input_format = models.TextField()
    output_format = models.TextField()
    sample_input = models.TextField()
    sample_output = models.TextField()
    test_cases = models.TextField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Problem, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class UserProblem(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} -> {self.problem}'

    # def get_problems(request):
    #     problems = [i.title for i in Problem.objects.filter(user=request.user)]
    #     return problems

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


# class CustomUser(AbstractUser):
#     profile_picture = models.ImageField(upload_to='profile_pictures')
#     gender = models.CharField(max_length=20, choices=(('male', 'Erkak'), ('female', 'Ayol')), default='male')


class CustomUser(AbstractUser):
    email = models.EmailField()
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    gender = models.CharField(max_length=10, choices=(('male', 'Male'), ('female', 'Female')))
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    verification_code = models.CharField(max_length=6, blank=True, null=True)
    email_verified = models.BooleanField(default=False)
    # joined_date = models.DateTimeField(auto_now_add=True, default=timezone.now)
    # last_login = models.DateTimeField()

users/forms.py
from django import forms
from django.contrib.auth import login

from users.models import CustomUser


# class UserCreateForm(forms.Form):
#     username = forms.CharField(max_length=150)
#     email = forms.EmailField()
#     first_name = forms.CharField(max_length=150)
#     last_name = forms.CharField(max_length=150)
#     password = forms.CharField(max_length=128)
#
#     def save(self):
#         username = self.cleaned_data['username']
#         firstname = self.cleaned_data['first_name']
#         lastname = self.cleaned_data['last_name']
#         email = self.cleaned_data['email']
#         password = self.cleaned_data['password']
#
#         user = CustomUser.objects.create(
#             username=username,
#             first_name=firstname,
#             last_name=lastname,
#             email=email,
#             is_staff=True,
#             is_superuser=True
#         )
#         user.set_password(password)
#
#         user.save()

# class UserCreateForm(forms.ModelForm):
#     class Meta:
#         model = CustomUser
#         fields = ('username','email','first_name','last_name', 'gender', 'password')
#
#     def save(self, commit=True):
#         user = super().save(commit)
#
#         gender = self.cleaned_data['gender']
#         if gender == 'male':
#             user.profile_picture = 'profile_pictures/default_boy_pic.jpg'
#         elif gender == 'female':
#             user.profile_picture = 'profile_pictures/default_girl_pic.jpg'
#
#         user.set_password(self.cleaned_data['password'])
#         user.save()
#         return user

from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

# class UserCreateForm(UserCreationForm):
#     class Meta:
#         model = CustomUser
#         fields = ('username', 'email', 'first_name', 'last_name', 'gender')
#
#     def clean_email(self):
#         email = self.cleaned_data.get('email')
#         if CustomUser.objects.filter(email=email).exists():
#             raise forms.ValidationError("This email address is already in use.")
#         return email
#
#     def save(self, commit=True):
#         user = super().save(commit=False)
#
#         gender = self.cleaned_data.get('gender')
#         if gender:
#             if gender == 'male':
#                 user.profile_picture = 'profile_pictures/default_boy_pic.jpg'
#             elif gender == 'female':
#                 user.profile_picture = 'profile_pictures/default_girl_pic.jpg'
#         if commit:
#             user.save()
#         return user


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
from .models import CustomUser
import random


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'gender')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)

        gender = self.cleaned_data.get('gender')
        if gender:
            if gender == 'male':
                user.profile_picture = 'profile_pictures/default_boy_pic.jpg'
            elif gender == 'female':
                user.profile_picture = 'profile_pictures/default_girl_pic.jpg'

        user.verification_code = generate_verification_code()

        if commit:
            user.save()
            self.send_verification_email(user)
        return user

    def send_verification_email(self, user):
        subject = "Email Verification"
        message = f"Your verification code is {user.verification_code}"
        from_email = "your_email@example.com"
        recipient_list = [user.email]
        send_mail(subject, message, from_email, recipient_list)


def generate_verification_code():
    return str(random.randint(100000, 999999))


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')




# class UserLoginForm(forms.Form):
#     username = forms.CharField(max_length=150)
#     password = forms.CharField(max_length=128)
#
#     # def clean(self):
    #     username = self.cleaned_data.get('username')
    #     password = self.cleaned_data.get('password')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, get_user_model

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import CustomUser
from django.shortcuts import render, redirect
from django.views import View
from users.forms import UserCreateForm, UserUpdateForm
from django.contrib.auth import login



# class RegisterView(View):
#     def get(self, request):
#         create_user = UserCreateForm()
#
#         context = {
#             'form':create_user
#         }
#         return render(request=request, template_name='users/register.html', context=context)
#
#     def post(self, request):
#         create_form = UserCreateForm(data=request.POST)
#
#         if create_form.is_valid():
#             create_form.save()
#             return redirect('problems:problem_list')
#         else:
#             context = {
#                 'form': create_form
#             }
#             return render(request=request, template_name='users/register.html', context=context)




class RegisterView(View):
    def get(self, request):
        create_user = UserCreateForm()
        context = {
            'form': create_user
        }
        return render(request=request, template_name='users/register.html', context=context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)
        if create_form.is_valid():
            user = create_form.save()
            # login(request, user)
            return redirect('users:verify_email')
        else:
            context = {
                'form': create_form
            }
            return render(request=request, template_name='users/register.html', context=context)


# class LoginView(View):
#     def get(self, request):
#         login_user = UserLoginForm()
#         context = {
#             'form': login_user
#         }
#         return render(request=request, template_name='users/login.html', context = context)
#
#     def post(self, request):
#         # login_form = UserLoginForm(data=request.POST)
#
#         login_form = AuthenticationForm(data=request.POST)
#
#         if login_form.is_valid():
#             # log in the user
#             print('salom dunyo')
#             return redirect('users:register')
#         else:
#             print('nima gap ozi')
#             return render(request, 'users/login.html',{'login_form': login_form})
#
#




class LoginView(View):
    def get(self, request):
        # login_form = UserLoginForm()
        login_form = AuthenticationForm()

        return render(request=request, template_name='users/login.html',context= {'form' : login_form})

    def post(self, request):
        # print(request.POST['username'], request.POST['password'])

        # login_form = UserLoginForm(data=request.POST)

        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You are now logged in')

            return redirect('problems:problem_list')
        else:
            return render(request=request, template_name='users/login.html',context= {'form' : login_form})

# class ProfileView(View):
#     def get(self, request):
#         user = request.user
#         if not user.is_authenticated:
#             return redirect('users:login')
#
#         return render(request, 'users/profile.html', {'user': request.user})


class ProfileView(LoginRequiredMixin,View):
    def get(self, request):
        return render(request, 'users/profile.html', {'user': request.user})



class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You have been logged out.')
        return redirect('landing_page')


class ProfileUpdateView(LoginRequiredMixin,View):
    def get(self, request):
        form = UserUpdateForm(instance=request.user)

        return render(request, 'users/profile_edit.html', {'form': form})

    def post(self, request):
        form = UserUpdateForm(
            instance = request.user,
            data = request.POST,
            files = request.FILES
        )

        if form.is_valid():
            form.save()
            messages.success(request, 'You have been updated successfully.')
            return redirect('users:profile')

        return render(request, 'users/profile_edit.html', {'form': form})


User = get_user_model()

def verify_email(request):
    if request.method == 'POST':
        code = request.POST.get('verification_code')
        try:
            user = User.objects.get(verification_code=code)
            user.email_verified = True
            user.verification_code = None  # Clear the verification code
            user.save()
            login(request, user)
            messages.success(request, 'Your email has been verified!')
            return redirect('problems:problem_list')
        except User.DoesNotExist:
            messages.error(request, 'Invalid verification code.')
    return render(request, 'users/verify_email.html')

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login page {% endblock %}


{% block content %}

    <h3>Login page</h3>
    <div class="row">
        <div class="col-4">
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary">Log in</button>
                <span class="ms-4">
                    No account? <a href="{% url 'users:register' %}">get register now</a>
                </span>
                <span class="ms-4">
                    Forget password? <a href="{% url 'users:password_reset' %}">reset now</a>
                </span>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Profile Page {% endblock %}

{% block content %}

    <div class="row d-flex justify-content-center">

        <div class="col-md-4">
            <div class="card text-center shadow-sm">
                <div class="card-body">
                    <div class="image mb-3">
                        <img class="rounded-circle" src="{{ user.profile_picture.url }}" alt="Profile Picture"
                             width="150" height="150">
                    </div>
                    <h4 class="card-title">{{ user.first_name }} {{ user.last_name }}</h4>
                    <h6 class="card-subtitle text-muted">@{{ user.username }}</h6>
                    <p class="card-text mt-2">{{ user.email }}</p>
                    <a class="btn btn-primary mt-3" href="{% url 'users:profile-edit' %}">Edit Profile</a>
                </div>
                <div class="card-footer text-muted">
                    <div class="d-flex justify-content-center">
                        <a href="#" class="btn btn-social-icon btn-twitter mx-1"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="btn btn-social-icon btn-facebook mx-1"><i class="fa fa-facebook-f"></i></a>
                        <a href="#" class="btn btn-social-icon btn-instagram mx-1"><i class="fa fa-instagram"></i></a>
                        <a href="#" class="btn btn-social-icon btn-linkedin mx-1"><i class="fa fa-linkedin"></i></a>
                    </div>
                    <div class="mt-3">
                        <small>Joined: {{ user.date_joined|date:"M Y" }}</small>
                    </div>
                    <div class="mt-3">
                        <small><a href="{% url 'users:password_change' %}">Change password</a></small>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h4 class="card-title">Solved Problems</h4>
                    {% if user.userproblem_set.all %}
                        <ul class="list-group list-group-flush mt-3">
                            {% for user_problem in user.userproblem_set.all %}
                                <li class="list-group-item"> {{ user_problem.problem.id }}:  <a style="color:black; text-decoration: none" href="{% url 'problems:problem_detail' user_problem.problem.id %}">{{ user_problem.problem.title     }}</a></li>

                            {% endfor %}
                        </ul>
                    {% else %}
                        <p class="mt-3">No problems solved yet.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Profile {% endblock %}

{% block content %}

    <h3>Edit Profile Page</h3>
    <div class="row">
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary" type="submit">save changes</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block title %} Register page {% endblock %}


{% block content %}
{% load crispy_forms_tags %}

<h3>Register page</h3>
{#<div class="row">#}
{#    <div class="col-4">#}
{#        <form method="post" action="{% url 'users:register' %}">{% csrf_token %}#}
{#            {{ form | crispy }}#}
{#            <button type="submit" class="btn btn-primary"> Yuborish </button>#}
{#        </form>#}
{#    </div>#}
{#</div>#}

<div class="row">
    <div class="col-6">
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
{#        <div>#}
{#            <label for="id_password1">Password:</label>#}
{#            <input type="password" name="password1" id="id_password1">#}
{#            <span class="password-eye" onclick="togglePasswordVisibility('id_password1')">👁️</span>#}
{#        </div>#}
{#        <div>#}
{#            <label for="id_password2">Confirm Password:</label>#}
{#            <input type="password" name="password2" id="id_password2">#}
{#            <span class="password-eye" onclick="togglePasswordVisibility('id_password2')">👁️</span>#}
{#        </div>#}
        <button type="submit">Register</button>
    </form>


    </div>
    </div>
{% endblock %}

users/templates/users/verify_email.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Verify Email {% endblock %}


{% block content %}
    <h2>Verify Your Email</h2>
    <form method="post">
        {% csrf_token %}
        <label for="verification_code">Verification Code:</label>
        <input type="number" id="verification_code" name="verification_code" required>
        <button type="submit">Verify</button>
    </form>
{% endblock %}