djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from djangoProject.views import landing_page

from problems.views import problem_list,problem_detail
from submissions.views import submit_code, submission_result

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    # path('home/', home, name='home'),
    path('users/', include('users.urls'), name='users'),
    path('', include('problems.urls'), name='problems'),
    path('', include('submissions.urls'), name='submissions'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problems/urls.py
# problems/urls.py
from django.urls import path
from . import views

app_name = 'problems'

urlpatterns = [
    path('problems/', views.problem_list, name='problem_list'),
    path('<int:pk>/', views.problem_detail, name='problem_detail'),
    path('problems/<slug>/', views.theme_list, name='problem-of-theme'),
]

users/urls.py
from django.contrib.auth.views import (PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)
from django.urls import path, reverse_lazy

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView, verify_email

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('verify-email/', verify_email, name='verify_email'),

    path('password-change/', PasswordChangeView.as_view(), name="password_change"),
    path('password-change-done/', PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name="password_reset"),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url = reverse_lazy("users:password_reset_complete")), name="password_reset_confirm"),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

templates/base.html
{% load static %}
{#{% url 'home' as home_page_url %}#}
{% url 'problems:problem_list' as problems_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile_edit' as profile_edit_page_url %}

<!DOCTYPE html>
<html lang="en">
<head>

{# https://getbootstrap.com/ #}
    <meta charset="UTF-8">
    <title>{% block title %} Solve Pazzle {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.7/codemirror.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.7/theme/dracula.min.css">
    <style>
        a {
            text-decoration: none;
        }
        .block_css{
            margin: 0;
            padding: 0;
        }
        .border-right{
            border-right: 2px solid #e8e0e0;
        
        }
        .password-eye {
            cursor: pointer;
        }
    </style>
</head>
<body class="mx-5 pe-2">
<nav class="navbar navbar-expand-lg mb-4 bg-" style="background-color: #e3f2fd;" >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">KodYoz.uz</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == problems_page_url %} active {% endif %}" aria-current="page" href="{{ problems_page_url }}">Masalalar</a>
        </li>
{#          <li class="nav-item">#}
{#              <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="https://www.w3schools.com/quiztest/quiztest.asp?qtest=PYTHON">Exam</a>#}
{#          </li>#}

      </ul>
          <form class="d-flex me-3" role="search" action="{{ problems_page_url }}">
            <input class="form-control me-1" type="search" placeholder="Search" name="q" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>

        <div class="me-5 pe-4" >
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle {% if request.path == profile_edit_page_url or request.path == profile_page_url  %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{ request.user.username }}
                      </a>
                      <ul class="dropdown-menu" style="width: 10px">
                        <li><a class="dropdown-item" href="{{ profile_page_url }}">Profile</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                      </ul>
                    </li>
                </ul>
            {% else %}

                <a href="{% url 'users:login' %}" class="btn btn-outline-primary">Login</a>
            {% endif %}

        </div>


    </div>
  </div>
</nav>


<div class="container ">
    {% if messages %}
        <div class="mt-3">
            {% for message in messages %}

                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>

    {% endif %}
    {% block content %} {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="{% static 'js/script.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.7/codemirror.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.7/mode/python/python.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.7/mode/clike/clike.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.7/mode/javascript/javascript.min.js"></script>

<script>
    var myCodeMirror = CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,
        mode: "python",
        theme: "dracula"
    });
    document.getElementById('language').addEventListener('change', function() {
        var language = this.value;
        var mode = "python";
        if (language === 'java') {
            mode = 'text/x-java';
        } else if (language === 'cpp') {
            mode = 'text/x-c++src';
        } else if (language === 'javascript') {
            mode = 'javascript';
        }
        myCodeMirror.setOption('mode', mode);
    });
</script>
    <script>
        function togglePasswordVisibility(fieldId) {
            const field = document.getElementById(fieldId);
            if (field.type === 'password') {
                field.type = 'text';
            } else {
                field.type = 'password';
            }
        }
    </script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home page{% endblock title %}


{% block content %}
    <div class="container posts-content">
    <div class="row">
        <div class="col-lg-6">
        <h3 class="mb-3">All reviews</h3>
            {% for review in page_obj %}

                <div class="card mb-4">
                  <div class="card-body">
                    <div class="media mb-3">
                      <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                      <div class="media-body ml-3">
                          {{ review.user.username }}
                        <div class="text-muted small">{{ review.created_at |date:"d M Y "}}</div>
                      </div>
                    </div>
                    <p>
                      {{ review.comment | truncatechars:250}}
                    </p>
                      <img class="cover-pic center"  src="{{ review.book.cover_picture.url }}" alt="{{ review.book.title }}">
                  </div>

                </div>
            {% endfor %}
        </div>
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}

                <li class="page-item active">
                    <a href="#" class="page-link">{{ page_obj.number }}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>

    </div>
</div>
{% endblock %}

templates/landing_page.html
{% extends 'base.html' %}

{% block content %}
    <h1>Landing page</h1>
    <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A fugit ipsam quaerat saepe. Ad, adipisci animi beatae cum est excepturi itaque minima nam nostrum perspiciatis quaerat quo temporibus unde. Doloribus.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A fugit ipsam quaerat saepe. Ad, adipisci animi beatae cum est excepturi itaque minima nam nostrum perspiciatis quaerat quo temporibus unde. Doloribus.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A fugit ipsam quaerat saepe. Ad, adipisci animi beatae cum est excepturi itaque minima nam nostrum perspiciatis quaerat quo temporibus unde. Doloribus.
    </p>
{% endblock %}